---
title: "demo"
author: "Henry"
date: "1/12/2021"
output: html_document
---
```{r}
## Which ones do we actually need?
library(chron)
library(devtools)
library(tidyr)
library(data.table)
library(ggplot2)
library(gganimate)
library(randomcoloR)
## We definitely need these
library(dplyr)
library(plotly)
source("viz.R")
```

```{r}
filedir = "C:/Users/heqin/OneDrive/Desktop/for-henry (2)/res.RDS"
res = readRDS(filedir)
```

```{r}

  numclust = res$numclust
  pie_table <- data.frame(res$pie)
  pie_table <- setDT(pie_table, keep.rownames = "Time")[]
  colnames(pie_table) <- c("Time", paste0("cluster_", 1:numclust))
  ## Reshape it to 3 columns as described above
  pie_table <- pie_table%>%
    gather(var,val,-c(1))%>%
    separate(var,c("type","cluster"))%>%
    .[-2]
  colnames(pie_table) <- c("Time", "Cluster","Prob")
  pie_table
```

```{r}
myColor <- randomcoloR::distinctColorPalette(k = numclust + 1)
key = highlight_key(pie_table,~Cluster)
pie_plot <- plot_ly(key)%>%
    group_by(Cluster)%>%
    add_lines(x = ~Time , y = ~Prob,color = ~Cluster, colors = myColor[2:numclust + 1] ,)%>%
    add_segments(x = ~Time, xend = ~Time, y = 0, yend = 1, frame = ~Time,showlegend = FALSE, color = myColor[1],showlegend = FALSE)
pie_plot <- pie_plot%>%layout(
    xaxis = list(
      type = "date",
      tickformat = "%d%M%Y",showticklabels = FALSE,showgrid = FALSE),
    yaxis = list(showgrid = FALSE,title = c("Cluster Probabilities"),titlefont = list(size = 8)),
    showlegend = FALSE,
    title = ""
  )
pie_plot <- pie_plot%>%highlight(
    on = "plotly_click", 
    off = "plotly_doubleclick",
    selectize = FALSE, 
    dynamic = FALSE, 
    persistent = FALSE,
    showlegend = F
  )
pie_plot
```

```{r}
as.data.frame(res$X)[,c(1,2,5)]
```
```{r}
covariates_table = function(res){
  covariates = res$X
  covariates = as.data.frame(covariates)
  covariates = setDT(covariates, keep.rownames = "Time")[]
  covariates <- covariates%>%
    gather(var,val,-c(1))
  colnames(covariates) = c("Time","Trace","Value")
  return(covariates)
}

covariates = covariates_table(res)
make_covariates_plot(covariates)
```

```{r}
cv_plot <- plot_ly(covariates)%>%
    group_by(Trace)%>%
    add_lines(x = ~Time , y = ~Value,color = "grey50",opacity = 0.1)%>%
    add_segments(x = ~Time, xend = ~Time, y = -6, yend = 6, frame = ~Time,showlegend = FALSE, color = myColor[1],showlegend = FALSE)
  
  # modify the x-axis  
  cv_plot <- cv_plot%>%layout(
    xaxis = list(
      type = "date",
      tickformat = "%d%M%Y",showticklabels = FALSE,showgrid = FALSE),
    yaxis = list(showgrid = FALSE, title = c("EnvironmenTal Covariates"),titlefont = list(size = 8)),
    showlegend = FALSE
  )
cv_plot
```

```{r}
s = c(1,2,3)
as.data.frame(res$X)[,s]
```

```{r}
data
```

```{r}
s = c(1,2,3)
covariates = res$X[,s]
covariates = as.data.frame(covariates)
covariates = setDT(covariates, keep.rownames = "Time")[]
covariates <- covariates%>%
  gather(var,val,-c(1))
colnames(covariates) = c("Time","Trace","Value")
covariates
```

```{r}
subplot(pie_plot,cv_plot,shareX = TRUE,heights = c(0.6,0.4),nrows = 2)
```

