---
title: "Plots"
author: "Henry He"
date: "2020/7/30"
output: html_document
---
```{r}
library(chron)
library(devtools)
library(dplyr)
library(tidyr)
library(data.table)
library(ggplot2)
library(gganimate)
library(lubridate)
library(plotly)
```

#Load data 
```{r}
filedir = "~/Downloads/for-henry/res.RDS"
filedir =  file.choose() ## filedir = "./res.RDS"## file.choose()
res = readRDS(filedir)
countslist <- res$countslist
pie_table <- data.frame(res$pie)
pie_table <- setDT(pie_table, keep.rownames = "Time")[]
colnames(pie_table)<-c("Time","cluster_1","cluster_2","cluster_3","cluster_4","cluster_5","cluster_6","cluster_7","cluster_8","cluster_9","cluster_10")
# pie 
pie_table <-pie_table%>%
  gather(var,val,-c(1))%>%
  separate(var,c("type","cluster"))
colnames(pie_table) <- c("Time","Type","Cluster","Prob")
pie_table

# Henry's first version 
ylist <- res$ylist




microbenchmark::microbenchmark({
  print(Sys.time())
  y_table2 <- data.frame()
  rept2 <- c()
  for(i in ylist){
    rept2 <- c(rept2, nrow(i))
    y_table2 <- rbind(y_table2,data.frame(i)) ## inefficient
  }
},times=3)

## SH: better than above
y_table2 <- matrix(NA, nrow=sum(sapply(ylist, nrow)), ncol= ncol(ylist[[1]]))
irow0 = 0
for(i in ylist){
  irow0 = max(irow0) + 1:(nrow(i))
  y_table2[irow0,] = i ## inefficient
}
y_table2 <- as.data.frame(y_table2)

## SH: Better (=cleaner, readable, faster) code for the above.
ylist <- res$ylist
microbenchmark::microbenchmark({
  y_table = do.call(rbind, ylist) %>% as.data.frame()
}, times=10)
y_table


## SH: I brought this over from your older script
x <- data.frame(res$pie)
x <- setDT(x, keep.rownames = "Time")[]

time <- rep(x$Time,times = rept2) ## SH: what is x$Time?  The rest of the code
                                 ## doesn't run because of this!
y_table$time  <- time
df <- c(matrix(unlist(countslist), ncol=1))
df <- df/max(unlist(countslist))
#df <- sqrt(df) *10
y_table$countslist <- df
y_table
y_table[1:50000,]

## pie_table[1,]
## rep(pie_table[1,],3)
## nrow(pie_table)

## repeat_time <- rep(rept,10)

## rep(row.names(pie_table),repeat_time)
#y_table<- y_table[1:50000,]
## pie_table$Time[[1]]

```

```{r}

dim <- dim(y_table)
y <- matrix(NA,nrow = dim[1],ncol = dim[2])
colnames(y) = colnames(y_table)
head(y)

```


# Generate Plots 
```{r}


p1<-plot_ly(y_table, y= ~chl_small,x = ~diam_mid, frame = ~time, size = ~countslist,type = 'scatter', mode = 'markers',sizes = c(0,2000), opacity = 0.5,alpha = 0.3)
p2<-plot_ly(y_table, y = ~pe, x = ~chl_small, frame = ~time, size = ~ countslist,type = 'scatter', mode = 'markers',alpha = 0.3, opacity=0.5,sizes = c(0,2000))
p3<-plot_ly(y_table, x= ~pe,y = ~diam_mid, frame = ~time,size = ~ countslist,type = 'scatter', mode = 'markers',opacity=0.5,sizes = c(0,2000),alpha = 0.3)
p <- subplot(p1,p2,p3)
p
  
## SH: first try at making time series plot sync with scatterplots
colnames(pie_table)[1] = "Time"
times = pie_table %>% select(Time) %>% unlist() %>% unique()
pie_table_large_list <- lapply(times[1:11], function(mytime){
  return(cbind(time = mytime, pie_table))
})
pie_table_large <- do.call(rbind, pie_table_large_list)
pie_table_large %>% dim()
pie_table_large %>% object.size() %>% format("Mb")
pie_table_large
prob <- highlight_key(pie_table_large, ~Cluster)
p4 <- plot_ly(prob, frame = ~time) %>%
  group_by(Cluster) %>%
  add_lines(x = ~Time, y = ~Prob, color = ~Cluster)
p4
pie_table_large %>% select(time) %>% unique()
y_table %>% select(time) %>% unique()
subplot(p, p4,
        titleX = TRUE, titleY = TRUE, nrows = 2)
```



```{r}

# new table 

dims = c(1,2)
ylist = res$ylist
countslists = res$countslist
TT <- unique(y_table$time)

#three tables to use later 
diam_mid_chl_small_table <- data.frame()
pe_chl_small_table <- data.frame()
diam_mid_pe_table = data.frame()






for (tt in TT){
  
   ## Extract data
  y = ylist[[tt]][,dims]



  ## Temporary
  y = ylist[[tt]][,dims]
  cnames = colnames(y)
  counts = countslist[[tt]]
  yy = cbind(y, counts)
  yy = yy %>% tibble::as_tibble() %>%
    ## group_by(diam_mid, chl_small) %>%
    dplyr::group_by_at(c(1,2)) %>%
    dplyr::summarise(counts = sum(counts)) %>% as.matrix
  counts = yy[,3]
  y = yy[,1:3]
  times <- rep(tt,nrow(y))
  y = cbind(y, times)
  y = as.data.frame(y)
  y$diam_mid = as.numeric(y$diam_mid)
  y$chl_small = as.numeric(y$chl_small)
  y$counts = as.numeric(y$counts)
  diam_mid_chl_small_table <- rbind(diam_mid_chl_small_table,y)
  
  
}


dims = c(2,3)
for (tt in TT){
   ## Extract data
  y = ylist[[tt]][,dims]



  ## Temporary
  y = ylist[[tt]][,dims]
  cnames = colnames(y)
  counts = countslist[[tt]]
  yy = cbind(y, counts)
  yy = yy %>% tibble::as_tibble() %>%
    ## group_by(diam_mid, chl_small) %>%
    dplyr::group_by_at(c(1,2)) %>%
    dplyr::summarise(counts = sum(counts)) %>% as.matrix
  y = yy[,1:3]
  times <- rep(tt,nrow(y))
  y = cbind(y, times)
  y = as.data.frame(y)
  y$pe = as.numeric(y$pe)
  y$chl_small = as.numeric(y$chl_small)
  y$counts = as.numeric(y$counts)
  pe_chl_small_table <- rbind(pe_chl_small_table,y)
}


dims = c(1,3)

for (tt in TT){
   ## Extract data
  y = ylist[[tt]][,dims]



  ## Temporary
  y = ylist[[tt]][,dims]
  cnames = colnames(y)
  counts = countslist[[tt]]
  yy = cbind(y, counts)
  yy = yy %>% tibble::as_tibble() %>%
    ## group_by(diam_mid, chl_small) %>%
    dplyr::group_by_at(c(1,2)) %>%
    dplyr::summarise(counts = sum(counts)) %>% as.matrix
  y = yy[,1:3]
  times <- rep(tt,nrow(y))
  y = cbind(y, times)
  y = as.data.frame(y)
  y$pe = as.numeric(y$pe)
  y$diam_mid = as.numeric(y$diam_mid)
  y$counts = as.numeric(y$counts)
  diam_mid_pe_table <- rbind(diam_mid_pe_table,y)
}


```
```{r}
y_table
# centers
times <- unique(y_table$time)
mn <- res$mn
m <- matrix(NA,nrow = 296*10, ncol = 4)
j = 1
for (i in 1:10){
  temp <- mn[,,i]
  m[(j:(j+295)),1:3] <-temp
  m[(j:(j+295)),4] <- paste("Cluster",as.character(i))
  j = j +296
  
}
m = as.data.frame(m)
colnames(m) = c("diam_mid", "chl_small","pe","Cluster")
m$times = times
m
plot_ly(m,x = ~diam_mid,y=~pe,frame = ~times,type = "scatter",mode = 'markers+text',
        textposition = "bottom center",hoverinfo = "x + y",text = ~Cluster,showlegend = FALSE)
```

```{r}

p1<-plot_ly(diam_mid_chl_small_table, y= ~chl_small,x = ~diam_mid, frame = ~times, size = ~counts,type = 'scatter', mode = 'markers',sizes = c(0,2000), opacity = 0.5,alpha = 0.3)
p1
p2<-plot_ly(pe_chl_small_table, y = ~pe, x = ~chl_small, frame = ~times, size = ~ counts,type = 'scatter', mode = 'markers',alpha = 0.3, opacity=0.5,sizes = c(0,2000))
p3<-plot_ly(diam_mid_pe_table, x= ~pe,y = ~diam_mid, frame = ~times,size = ~ counts,type = 'scatter', mode = 'markers',opacity=0.5,sizes = c(0,2000),alpha = 0.3)
p <- subplot(p1,p2,p3)





## SH: first try at making time series plot sync with scatterplots
colnames(pie_table)[1] = "Time"
times = pie_table %>% select(Time) %>% unlist() %>% unique()
pie_table_large_list <- lapply(times[1:11], function(mytime){
  return(cbind(time = mytime, pie_table))
})
pie_table_large <- do.call(rbind, pie_table_large_list)
pie_table_large %>% dim()
pie_table_large %>% object.size() %>% format("Mb")
pie_table_large
prob <- highlight_key(pie_table_large, ~Cluster)
p4 <- plot_ly(prob, frame = ~time) %>%
  group_by(Cluster) %>%
  add_lines(x = ~Time, y = ~Prob, color = ~Cluster)%>%
  add_segments(x = ~time,xend = ~time, y = 0,yend = 1,frame = ~time)%>%
p4
pie_table_large %>% select(time) %>% unique()
y_table %>% select(time) %>% unique()



subplot(p, p4,
        titleX = TRUE, titleY = TRUE, nrows = 2)
```

